apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-deploy
  labels:
    app: financeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: financeapp
  template:
    metadata:
      labels:
        app: financeapp
    spec:
      containers:
      - name: financeme-container
        image: manjunathachar/financeapp:latest
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: finance-service
  labels:
    app: financeapp
spec:
  selector:
    app: financeapp
  type: NodePort
  ports:
  - nodePort: 31664
    port: 8083
    targetPort: 8083
